### ISSUE TITLE
Minor nits

### ISSUE THREAD

**Issue by Quuxplusone** [tobias-loew/hop#1]
- Should `#include <limits>`, to satisfy GCC.

- `HOP_MAX_DEDUDCABLE_TYPES` is misspelled; should be `HOP_MAX_DEDUCIBLE_TYPES`

- in the README, `intependently` is misspelled; should be `independently`

- It feels to me like you might want to add something like this `match_tag_t` https://godbolt.org/z/WMKdfT so that the client can say "I want this function to participate in overload resolution _only if_ it matches this specific pattern out of the overload set I've crafted." All the README examples seem to be focused on making "one entry point to rule them all" and then using `if constexpr` inside to break out the handling for the different specific patterns.

**Comment by tobias-loew** [comment]
Thanks a lot for your comments and the detailed example on godbolt.
I integrated `match_tag` and also removed the usage of `decltype` from the user-interface. See 6944f4510a5b3b807e6005239d782402a56dcc25.
I'll close the issue.
